# $Id: 000_compile-core.t,v 1.50.2.10 2011/06/25 10:49:41 ak Exp $
use strict;
use warnings;
use lib qw(./t/lib ./dist/lib ./src/lib);
use Test::More;

my $Modules = [ qw{
	Kanadzuchi
	Kanadzuchi::Address
	Kanadzuchi::Archive
	Kanadzuchi::Archive::Gzip
	Kanadzuchi::BdDR
	Kanadzuchi::BdDR::BounceLogs
	Kanadzuchi::BdDR::Cache
	Kanadzuchi::BdDR::Page
	Kanadzuchi::BdDR::BounceLogs::Masters
	Kanadzuchi::BdDR::DailyUpdates
	Kanadzuchi::Config::TestRun
	Kanadzuchi::Crypt
	Kanadzuchi::Exceptions
	Kanadzuchi::ISO3166
	Kanadzuchi::Iterator
	Kanadzuchi::Log
	Kanadzuchi::Mail
	Kanadzuchi::Mail::Bounced
	Kanadzuchi::Mail::Bounced::Generic
	Kanadzuchi::Mail::Bounced::Yahoo
	Kanadzuchi::Mail::Group
	Kanadzuchi::Mail::Group::AE::Smartphone
	Kanadzuchi::Mail::Group::AL::Smartphone
	Kanadzuchi::Mail::Group::AL::WebMail
	Kanadzuchi::Mail::Group::AR::Cellphone
	Kanadzuchi::Mail::Group::AR::Smartphone
	Kanadzuchi::Mail::Group::AR::WebMail
	Kanadzuchi::Mail::Group::AT::Cellphone
	Kanadzuchi::Mail::Group::AT::Smartphone
	Kanadzuchi::Mail::Group::AU::Cellphone
	Kanadzuchi::Mail::Group::AU::Smartphone
	Kanadzuchi::Mail::Group::AU::WebMail
	Kanadzuchi::Mail::Group::AW::Cellphone
	Kanadzuchi::Mail::Group::BE::Smartphone
	Kanadzuchi::Mail::Group::BG::Cellphone
	Kanadzuchi::Mail::Group::BG::Smartphone
	Kanadzuchi::Mail::Group::BM::Smartphone
	Kanadzuchi::Mail::Group::BR::Cellphone
	Kanadzuchi::Mail::Group::BR::Smartphone
	Kanadzuchi::Mail::Group::BR::WebMail
	Kanadzuchi::Mail::Group::BS::Smartphone
	Kanadzuchi::Mail::Group::CA::Cellphone
	Kanadzuchi::Mail::Group::CA::Smartphone
	Kanadzuchi::Mail::Group::CA::WebMail
	Kanadzuchi::Mail::Group::CH::Cellphone
	Kanadzuchi::Mail::Group::CH::Smartphone
	Kanadzuchi::Mail::Group::CL::Smartphone
	Kanadzuchi::Mail::Group::CN::Smartphone
	Kanadzuchi::Mail::Group::CN::WebMail
	Kanadzuchi::Mail::Group::CO::Cellphone
	Kanadzuchi::Mail::Group::CO::Smartphone
	Kanadzuchi::Mail::Group::CR::Cellphone
	Kanadzuchi::Mail::Group::CZ::WebMail
	Kanadzuchi::Mail::Group::CZ::Smartphone
	Kanadzuchi::Mail::Group::DE::Cellphone
	Kanadzuchi::Mail::Group::DE::Smartphone
	Kanadzuchi::Mail::Group::DE::WebMail
	Kanadzuchi::Mail::Group::DK::Smartphone
	Kanadzuchi::Mail::Group::DO::Smartphone
	Kanadzuchi::Mail::Group::EC::Smartphone
	Kanadzuchi::Mail::Group::EG::Smartphone
	Kanadzuchi::Mail::Group::EG::WebMail
	Kanadzuchi::Mail::Group::ES::Cellphone
	Kanadzuchi::Mail::Group::ES::Smartphone
	Kanadzuchi::Mail::Group::ES::WebMail
	Kanadzuchi::Mail::Group::FR::Cellphone
	Kanadzuchi::Mail::Group::FR::Smartphone
	Kanadzuchi::Mail::Group::FR::WebMail
	Kanadzuchi::Mail::Group::GR::Smartphone
	Kanadzuchi::Mail::Group::GT::Smartphone
	Kanadzuchi::Mail::Group::HK::Smartphone
	Kanadzuchi::Mail::Group::HN::Smartphone
	Kanadzuchi::Mail::Group::HR::Cellphone
	Kanadzuchi::Mail::Group::HR::Smartphone
	Kanadzuchi::Mail::Group::HU::Smartphone
	Kanadzuchi::Mail::Group::ID::Smartphone
	Kanadzuchi::Mail::Group::IE::Cellphone
	Kanadzuchi::Mail::Group::IE::Smartphone
	Kanadzuchi::Mail::Group::IN::Cellphone
	Kanadzuchi::Mail::Group::IN::Smartphone
	Kanadzuchi::Mail::Group::IN::WebMail
	Kanadzuchi::Mail::Group::IL::Cellphone
	Kanadzuchi::Mail::Group::IL::Smartphone
	Kanadzuchi::Mail::Group::IL::WebMail
	Kanadzuchi::Mail::Group::IR::WebMail
	Kanadzuchi::Mail::Group::IS::Cellphone
	Kanadzuchi::Mail::Group::IS::Cellphone
	Kanadzuchi::Mail::Group::IT::Cellphone
	Kanadzuchi::Mail::Group::IT::Smartphone
	Kanadzuchi::Mail::Group::JM::Smartphone
	Kanadzuchi::Mail::Group::JP::Cellphone
	Kanadzuchi::Mail::Group::JP::Smartphone
	Kanadzuchi::Mail::Group::JP::WebMail
	Kanadzuchi::Mail::Group::KE::Smartphone
	Kanadzuchi::Mail::Group::KR::WebMail
	Kanadzuchi::Mail::Group::LB::Smartphone
	Kanadzuchi::Mail::Group::LK::Cellphone
	Kanadzuchi::Mail::Group::LK::Smartphone
	Kanadzuchi::Mail::Group::LU::Smartphone
	Kanadzuchi::Mail::Group::LV::WebMail
	Kanadzuchi::Mail::Group::MA::Smartphone
	Kanadzuchi::Mail::Group::MD::WebMail
	Kanadzuchi::Mail::Group::ME::Smartphone
	Kanadzuchi::Mail::Group::MK::Smartphone
	Kanadzuchi::Mail::Group::MO::Smartphone
	Kanadzuchi::Mail::Group::MU::Cellphone
	Kanadzuchi::Mail::Group::MX::Cellphone
	Kanadzuchi::Mail::Group::MX::Smartphone
	Kanadzuchi::Mail::Group::MY::Smartphone
	Kanadzuchi::Mail::Group::NG::Smartphone
	Kanadzuchi::Mail::Group::NI::Cellphone
	Kanadzuchi::Mail::Group::NI::Smartphone
	Kanadzuchi::Mail::Group::NL::Cellphone
	Kanadzuchi::Mail::Group::NL::Smartphone
	Kanadzuchi::Mail::Group::NO::Smartphone
	Kanadzuchi::Mail::Group::NO::WebMail
	Kanadzuchi::Mail::Group::NP::Cellphone
	Kanadzuchi::Mail::Group::NP::Smartphone
	Kanadzuchi::Mail::Group::NZ::Cellphone
	Kanadzuchi::Mail::Group::NZ::Smartphone
	Kanadzuchi::Mail::Group::NZ::WebMail
	Kanadzuchi::Mail::Group::OM::Smartphone
	Kanadzuchi::Mail::Group::PA::Smartphone
	Kanadzuchi::Mail::Group::PE::Smartphone
	Kanadzuchi::Mail::Group::PH::Smartphone
	Kanadzuchi::Mail::Group::PK::Smartphone
	Kanadzuchi::Mail::Group::PL::Cellphone
	Kanadzuchi::Mail::Group::PL::Smartphone
	Kanadzuchi::Mail::Group::PR::Cellphone
	Kanadzuchi::Mail::Group::PR::Smartphone
	Kanadzuchi::Mail::Group::PT::Smartphone
	Kanadzuchi::Mail::Group::PT::WebMail
	Kanadzuchi::Mail::Group::PY::Smartphone
	Kanadzuchi::Mail::Group::RO::Smartphone
	Kanadzuchi::Mail::Group::RO::WebMail
	Kanadzuchi::Mail::Group::RS::Smartphone
	Kanadzuchi::Mail::Group::RU::Smartphone
	Kanadzuchi::Mail::Group::RU::WebMail
	Kanadzuchi::Mail::Group::SA::Smartphone
	Kanadzuchi::Mail::Group::SE::Cellphone
	Kanadzuchi::Mail::Group::SE::Smartphone
	Kanadzuchi::Mail::Group::SG::Cellphone
	Kanadzuchi::Mail::Group::SG::Smartphone
	Kanadzuchi::Mail::Group::SG::WebMail
	Kanadzuchi::Mail::Group::SK::Smartphone
	Kanadzuchi::Mail::Group::SK::WebMail
	Kanadzuchi::Mail::Group::SR::Smartphone
	Kanadzuchi::Mail::Group::SV::Smartphone
	Kanadzuchi::Mail::Group::TH::Smartphone
	Kanadzuchi::Mail::Group::TH::WebMail
	Kanadzuchi::Mail::Group::TR::Smartphone
	Kanadzuchi::Mail::Group::TW::Smartphone
	Kanadzuchi::Mail::Group::TW::WebMail
	Kanadzuchi::Mail::Group::UA::Smartphone
	Kanadzuchi::Mail::Group::UG::Smartphone
	Kanadzuchi::Mail::Group::UK::Cellphone
	Kanadzuchi::Mail::Group::UK::Smartphone
	Kanadzuchi::Mail::Group::UK::WebMail
	Kanadzuchi::Mail::Group::US::Cellphone
	Kanadzuchi::Mail::Group::US::Smartphone
	Kanadzuchi::Mail::Group::US::WebMail
	Kanadzuchi::Mail::Group::UY::Smartphone
	Kanadzuchi::Mail::Group::VE::Smartphone
	Kanadzuchi::Mail::Group::VN::Smartphone
	Kanadzuchi::Mail::Group::VN::WebMail
	Kanadzuchi::Mail::Group::ZA::Cellphone
	Kanadzuchi::Mail::Group::ZA::Smartphone
	Kanadzuchi::Mail::Group::ZA::WebMail
	Kanadzuchi::Mail::Group::Neighbor
	Kanadzuchi::Mail::Group::Cellphone
	Kanadzuchi::Mail::Group::Smartphone
	Kanadzuchi::Mail::Group::WebMail
	Kanadzuchi::Mail::Stored
	Kanadzuchi::Mail::Stored::BdDR
	Kanadzuchi::Mail::Stored::YAML
	Kanadzuchi::Mail::Why
	Kanadzuchi::Mail::Why::ContentError
	Kanadzuchi::Mail::Why::ExceedLimit
	Kanadzuchi::Mail::Why::Expired
	Kanadzuchi::Mail::Why::Filtered
	Kanadzuchi::Mail::Why::HostUnknown
	Kanadzuchi::Mail::Why::MailboxFull
	Kanadzuchi::Mail::Why::MailerError
	Kanadzuchi::Mail::Why::MesgTooBig
	Kanadzuchi::Mail::Why::NotAccept
	Kanadzuchi::Mail::Why::Rejected
	Kanadzuchi::Mail::Why::RelayingDenied
	Kanadzuchi::Mail::Why::SecurityError
	Kanadzuchi::Mail::Why::SystemError
	Kanadzuchi::Mail::Why::SystemFull
	Kanadzuchi::Mail::Why::UserUnknown
	Kanadzuchi::Mbox
	Kanadzuchi::MDA
	Kanadzuchi::MIME::Parser
	Kanadzuchi::Metadata
	Kanadzuchi::MTA
	Kanadzuchi::MTA::Courier
	Kanadzuchi::MTA::Exim
	Kanadzuchi::MTA::Fallback
	Kanadzuchi::MTA::Postfix
	Kanadzuchi::MTA::qmail
	Kanadzuchi::MTA::Sendmail
	Kanadzuchi::RFC2606
	Kanadzuchi::RFC2822
	Kanadzuchi::RFC3463
	Kanadzuchi::Statistics
	Kanadzuchi::Statistics::Stored
	Kanadzuchi::Statistics::Stored::BdDR
	Kanadzuchi::Statistics::Stored::YAML
	Kanadzuchi::String
	Kanadzuchi::Time
	Kanadzuchi::UI
	Kanadzuchi::UI::CLI
} ];

my $Optionals = [ qw{
	Kanadzuchi::Archive::Bzip2
	Kanadzuchi::Archive::Zip
	Kanadzuchi::MTA::JP::aubyKDDI
	Kanadzuchi::MTA::US::Google
	Kanadzuchi::MTA::US::Facebook
} ];

plan( tests => scalar(@$Modules) + scalar(@$Optionals) );
foreach my $module ( @$Modules ){ use_ok($module); }
foreach my $optmod ( @$Optionals )
{ 
	my $path = $optmod; $path =~ y{::}{/}; $path =~ s{\z}{.pm};
	my $dist = -d './dist/lib' ? './dist/lib' : './src/lib';
	ok( -f $dist.'/'.$path );
}

__END__
