INSERT INTO t_providers VALUES( 13, 'fastmail', 'FastMail', 0 );
INSERT INTO t_providers VALUES( 14, 'bol', 'BOL - Brasil', 0 );
INSERT INTO t_providers VALUES( 15, 'hush', 'Hushmail - Canada', 0 );
INSERT INTO t_providers VALUES( 16, 'netease', 'NetEase - China', 0 );
INSERT INTO t_providers VALUES( 17, 'seznam.cz', 'Seznam - Czech', 0 );
INSERT INTO t_providers VALUES( 18, 'gmx.de', 'GMX - Germany', 0 );
INSERT INTO t_providers VALUES( 19, 'gawab', 'Gawab.com - Egypt', 0 );
INSERT INTO t_providers VALUES( 20, 'walla', 'Walla! - Israel', 0 );
INSERT INTO t_providers VALUES( 21, 'ibibo', 'ibibo - India', 0 );
INSERT INTO t_providers VALUES( 22, 'iran.ir', 'iran.ir - Iran', 0 );
INSERT INTO t_providers VALUES( 23, 'aubykddi', 'au by KDDI - Japan', 0 );
INSERT INTO t_providers VALUES( 24, 'goo', 'goo - Japan', 0 );
INSERT INTO t_providers VALUES( 25, 'infoseek', 'Infoseek(Rakuten)- Japan', 0 );
INSERT INTO t_providers VALUES( 26, 'nifty', '@nifty - Japan', 0 );
INSERT INTO t_providers VALUES( 27, 'nttdocomo', 'NTT DoCoMo - Japan', 0 );
INSERT INTO t_providers VALUES( 28, 'softbank', 'SoftBank - Japan', 0 );
INSERT INTO t_providers VALUES( 29, 'willcom', 'SoftBank - Japan', 0 );
INSERT INTO t_providers VALUES( 30, 'emobile', 'EMOBILE(EMNET) - Japan', 0 );
INSERT INTO t_providers VALUES( 31, 'daum', 'Daum Communications - South Korea', 0 );
INSERT INTO t_providers VALUES( 32, 'empas', 'SK Communications - South Korea', 0 );
INSERT INTO t_providers VALUES( 33, 'inbokss', 'inbox.lv - Latvia', 0 );
INSERT INTO t_providers VALUES( 34, 'runbox', 'Runbox - Norway', 0 );
INSERT INTO t_providers VALUES( 35, 'coolkiwi', 'Cool Kiwi - New Zealand', 0 );
INSERT INTO t_providers VALUES( 36, 'qip', 'QIP.RU - Russia', 0 );
INSERT INTO t_providers VALUES( 37, 'runet', '@MAIL.RU - Russia', 0 );
INSERT INTO t_providers VALUES( 38, 'yandex', 'Yandex - Russia', 0 );
INSERT INTO t_providers VALUES( 39, 'singtel', 'inSing.com - Singapore', 0 );
INSERT INTO t_providers VALUES( 40, 'seednet', 'Digital United, SeedNet - Taiwan', 0 );
INSERT INTO t_providers VALUES( 41, 'gmx.com', 'GMX - United States, United Kingdom', 0 );
INSERT INTO t_providers VALUES( 42, 'spiedernetworks', 'PostMaster - United Kingdom', 0 );
INSERT INTO t_providers VALUES( 43, 'yipple', 'Yipple.com! - United Kingdom', 0 );
INSERT INTO t_providers VALUES( 44, 'telephonica', 'Telefonica O2', 0 );
INSERT INTO t_providers VALUES( 45, 'bluetie', 'BlueTie - United States', 0 );
INSERT INTO t_providers VALUES( 46, 'inbox.com', 'Inbox.com - United States', 0 );
INSERT INTO t_providers VALUES( 47, 'lavabit', 'Lavabit - United States', 0 );
INSERT INTO t_providers VALUES( 48, 'luxsci', 'LuxSci - United States', 0 );
INSERT INTO t_providers VALUES( 49, 'mail.com', 'Mail.com - United States', 0 );
INSERT INTO t_providers VALUES( 50, 'pobox', 'Pobox - United States', 0 );
INSERT INTO t_providers VALUES( 51, 'webmail.co.za', 'webmail.co.za - South Africa', 0 );
