INSERT INTO t_hostgroups VALUES( 1, 'undefined', 'Undefined host group', 0 );
INSERT INTO t_hostgroups VALUES( 2, 'reserved', 'RFC2606 or Reserved Top Level DNS Names', 0 );
INSERT INTO t_hostgroups VALUES( 3, '_unused-03', '', 0 );
INSERT INTO t_hostgroups VALUES( 4, '_unused-04', '', 0 );
INSERT INTO t_hostgroups VALUES( 5, '_unused-05', '', 0 );
INSERT INTO t_hostgroups VALUES( 6, '_unused-06', '', 0 );
INSERT INTO t_hostgroups VALUES( 7, 'cellphone', 'Japanese cellular phone', 0 );
INSERT INTO t_hostgroups VALUES( 8, 'smartphone', 'Smart phone address', 0 );
INSERT INTO t_hostgroups VALUES( 9, '_unused-09', '', 0 );
INSERT INTO t_hostgroups VALUES( 10, '_unused-10', '', 0 );
INSERT INTO t_hostgroups VALUES( 11, 'pc', 'PC address', 0 );
INSERT INTO t_hostgroups VALUES( 12, 'webmail', 'Free web-based e-mail service', 0 );
INSERT INTO t_hostgroups VALUES( 13, '_unused-13', '', 0 );
INSERT INTO t_hostgroups VALUES( 14, '_unused-14', '', 0 );
INSERT INTO t_hostgroups VALUES( 15, '_unused-15', '', 0 );
INSERT INTO t_hostgroups VALUES( 16, 'neighbor', 'Neighbors', 0 );
